[32m2024-08-01 00:11:40 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - 457d9575-29a4-4beb-bb3a-2fd08b64ed63 - 292910 - LOGS_CAPTURED - Started capturing logs in process (pid: 292910).
[32m2024-08-01 00:11:40 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - 457d9575-29a4-4beb-bb3a-2fd08b64ed63 - 292910 - dbt_run_op - STEP_START - Started execution of step "dbt_run_op".
[32m2024-08-01 00:11:40 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 457d9575-29a4-4beb-bb3a-2fd08b64ed63 - dbt_run_op - Executing command: dbt --no-use-colors --log-format json run --project-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt --profiles-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt
[32m2024-08-01 00:11:42 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 457d9575-29a4-4beb-bb3a-2fd08b64ed63 - dbt_run_op - Running with dbt=1.7.17
[32m2024-08-01 00:11:43 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 457d9575-29a4-4beb-bb3a-2fd08b64ed63 - dbt_run_op - Registered adapter: sqlserver=1.7.4
[32m2024-08-01 00:11:43 +0800[0m - dagster - [34mERROR[0m - [31mresource:dbt - 457d9575-29a4-4beb-bb3a-2fd08b64ed63 - dbt_run_op - Encountered an error:
Compilation Error in model asnaf_transformed (models/staging/asnaf_transformed.sql)
  unexpected char '#' at 41
    line 2
      materialized='ephemeral'  # Use ephemeral to avoid creating a new table[0m
[32m2024-08-01 00:11:45 +0800[0m - dagster - [34mERROR[0m - [31mppa_data_pipeline - 457d9575-29a4-4beb-bb3a-2fd08b64ed63 - 292910 - dbt_run_op - STEP_FAILURE - Execution of step "dbt_run_op" failed.

dagster_dbt.errors.DagsterDbtCliFatalRuntimeError: Fatal error in the dbt CLI (return code 2): Running with dbt=1.7.17 Registered adapter: sqlserver=1.7.4 Encountered an error:
Compilation Error in model asnaf_transformed (models/staging/asnaf_transformed.sql)
  unexpected char '#' at 41
    line 2
      materialized='ephemeral'  # Use ephemeral to avoid creating a new table

Stack Trace:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 494, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 198, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 167, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/ops.py", line 89, in dbt_run_op
    dbt_output = context.resources.dbt.run()
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 281, in run
    return self.cli("run", models=models, exclude=exclude, select=select, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 204, in cli
    return execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 238, in execute_cli
    for event in _core_execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 160, in _core_execute_cli
    raise DagsterDbtCliFatalRuntimeError(messages=messages)
[0m
