[32m2024-07-31 23:11:12 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - 149178 - LOGS_CAPTURED - Started capturing logs in process (pid: 149178).
[32m2024-07-31 23:11:12 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - 149178 - dbt_run_op - STEP_START - Started execution of step "dbt_run_op".
[32m2024-07-31 23:11:12 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - Executing command: dbt --no-use-colors --log-format json run --project-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt --profiles-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt
[32m2024-07-31 23:11:14 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - Running with dbt=1.7.17
[32m2024-07-31 23:11:15 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - Registered adapter: sqlserver=1.7.4
[32m2024-07-31 23:11:15 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - Unable to do partial parsing because saved manifest not found. Starting full parse.
[32m2024-07-31 23:11:16 +0800[0m - dagster - [34mWARNING[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - [WARNING]: Did not find matching node for patch with name 'asnaf_transformed' in the 'models' section of file 'models/staging/schema.yml'
[32m2024-07-31 23:11:16 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - Found 3 models, 4 tests, 1 source, 0 exposures, 0 metrics, 457 macros, 0 groups, 0 semantic models
[32m2024-07-31 23:11:16 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op
[32m2024-07-31 23:11:16 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op
[32m2024-07-31 23:11:16 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - Finished running  in 0 hours 0 minutes and 0.04 seconds (0.04s).
[32m2024-07-31 23:11:16 +0800[0m - dagster - [34mERROR[0m - [31mresource:dbt - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - dbt_run_op - Encountered an error:
Database Error
  ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.1.1' : file not found (0) (SQLDriverConnect)")[0m
[32m2024-07-31 23:11:18 +0800[0m - dagster - [34mERROR[0m - [31mppa_data_pipeline - 0860e92f-b0d0-4a98-b2dc-73baf42f5c98 - 149178 - dbt_run_op - STEP_FAILURE - Execution of step "dbt_run_op" failed.

dagster_dbt.errors.DagsterDbtCliFatalRuntimeError: Fatal error in the dbt CLI (return code 2): Running with dbt=1.7.17 Registered adapter: sqlserver=1.7.4 Unable to do partial parsing because saved manifest not found. Starting full parse. [WARNING]: Did not find matching node for patch with name 'asnaf_transformed' in the 'models' section of file 'models/staging/schema.yml' Found 3 models, 4 tests, 1 source, 0 exposures, 0 metrics, 457 macros, 0 groups, 0 semantic models   Finished running  in 0 hours 0 minutes and 0.04 seconds (0.04s). Encountered an error:
Database Error
  ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.1.1' : file not found (0) (SQLDriverConnect)")

Stack Trace:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 494, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 198, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 167, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/ops.py", line 89, in dbt_run_op
    dbt_output = context.resources.dbt.run()
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 281, in run
    return self.cli("run", models=models, exclude=exclude, select=select, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 204, in cli
    return execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 238, in execute_cli
    for event in _core_execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 160, in _core_execute_cli
    raise DagsterDbtCliFatalRuntimeError(messages=messages)
[0m
