[32m2024-07-31 23:34:50 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - f42cf8a4-c394-43df-97ae-7788b6f6530d - 205754 - LOGS_CAPTURED - Started capturing logs in process (pid: 205754).
[32m2024-07-31 23:34:50 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - f42cf8a4-c394-43df-97ae-7788b6f6530d - 205754 - dbt_run_op - STEP_START - Started execution of step "dbt_run_op".
[32m2024-07-31 23:34:50 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Executing command: dbt --no-use-colors --log-format json run --project-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt --profiles-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt
[32m2024-07-31 23:34:52 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Running with dbt=1.7.17
[32m2024-07-31 23:34:52 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Registered adapter: sqlserver=1.7.4
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Found 1 model, 1 source, 0 exposures, 0 metrics, 457 macros, 0 groups, 0 semantic models
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Concurrency: 1 threads (target='dev')
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - 1 of 1 START sql table model dbo_dbo.transform_data ............................ [RUN]
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mERROR[0m - [31mresource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - 1 of 1 ERROR creating sql table model dbo_dbo.transform_data ................... [ERROR in 0.11s][0m
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Finished running 1 table model in 0 hours 0 minutes and 0.37 seconds (0.37s).
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Completed with 1 error and 0 warnings:
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mERROR[0m - [31mresource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op -   Database Error in model transform_data (models/staging/transform_data.sql)
  ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'IF'. (156) (SQLMoreResults)")[0m
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op
[32m2024-07-31 23:34:53 +0800[0m - dagster - [34mINFO[0m - resource:dbt - f42cf8a4-c394-43df-97ae-7788b6f6530d - dbt_run_op - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[32m2024-07-31 23:34:54 +0800[0m - dagster - [34mERROR[0m - [31mppa_data_pipeline - f42cf8a4-c394-43df-97ae-7788b6f6530d - 205754 - dbt_run_op - STEP_FAILURE - Execution of step "dbt_run_op" failed.

dagster_dbt.errors.DagsterDbtCliHandledRuntimeError: Handled error in the dbt CLI (return code 1)

Stack Trace:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 494, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 198, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 167, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/ops.py", line 89, in dbt_run_op
    dbt_output = context.resources.dbt.run()
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 281, in run
    return self.cli("run", models=models, exclude=exclude, select=select, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 204, in cli
    return execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 238, in execute_cli
    for event in _core_execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 163, in _core_execute_cli
    raise DagsterDbtCliHandledRuntimeError(messages=messages)
[0m
