[32m2024-07-31 23:50:23 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - 242594 - LOGS_CAPTURED - Started capturing logs in process (pid: 242594).
[32m2024-07-31 23:50:23 +0800[0m - dagster - [34mDEBUG[0m - ppa_data_pipeline - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - 242594 - dbt_run_op - STEP_START - Started execution of step "dbt_run_op".
[32m2024-07-31 23:50:23 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Executing command: dbt --no-use-colors --log-format json run --project-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt --profiles-dir /home/mnshuhailey/dev/ppa-dbt-dagster/ppa_dbt
[32m2024-07-31 23:50:25 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Running with dbt=1.7.17
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Registered adapter: sqlserver=1.7.4
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Found 1 model, 1 source, 0 exposures, 0 metrics, 457 macros, 0 groups, 0 semantic models
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Concurrency: 1 threads (target='dev')
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - 1 of 1 START sql table model dbo_dbo.asnaf_transformed ......................... [RUN]
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mERROR[0m - [31mresource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - 1 of 1 ERROR creating sql table model dbo_dbo.asnaf_transformed ................ [ERROR in 0.13s][0m
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Finished running 1 table model in 0 hours 0 minutes and 0.39 seconds (0.39s).
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Completed with 1 error and 0 warnings:
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mERROR[0m - [31mresource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op -   Database Error in model asnaf_transformed (models/staging/asnaf_transformed.sql)
  ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'IF'. (156) (SQLMoreResults)")[0m
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op
[32m2024-07-31 23:50:26 +0800[0m - dagster - [34mINFO[0m - resource:dbt - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - dbt_run_op - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[32m2024-07-31 23:50:27 +0800[0m - dagster - [34mERROR[0m - [31mppa_data_pipeline - 13a3ea2a-3000-48bd-b28b-e032df10d5c0 - 242594 - dbt_run_op - STEP_FAILURE - Execution of step "dbt_run_op" failed.

dagster_dbt.errors.DagsterDbtCliHandledRuntimeError: Handled error in the dbt CLI (return code 1)

Stack Trace:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 494, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 198, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/plan/compute.py", line 167, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.10/dist-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/ops.py", line 89, in dbt_run_op
    dbt_output = context.resources.dbt.run()
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 281, in run
    return self.cli("run", models=models, exclude=exclude, select=select, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/resources.py", line 204, in cli
    return execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 238, in execute_cli
    for event in _core_execute_cli(
  File "/usr/local/lib/python3.10/dist-packages/dagster_dbt/core/utils.py", line 163, in _core_execute_cli
    raise DagsterDbtCliHandledRuntimeError(messages=messages)
[0m
